In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
patients = pd.read_csv("IndividualDetails.csv")

In [4]:
patients

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30/01/2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
1,1,KL-AL-P1,02/02/2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
2,2,KL-KS-P1,03/02/2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
3,3,DL-P1,02/03/2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15/03/2020,"Travelled from Austria, Italy"
4,4,TS-P1,02/03/2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02/03/2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8467,8468,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8468,8469,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8469,8470,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8470,8471,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8471,8472,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN

In [5]:
patients['current_status'].value_counts()

current_status
Hospitalized    8301
Recovered        139
Deceased          30
Migrated           1
Name: count, dtype: int64

In [10]:
total = patients.shape[0]
active = patients[patients['current_status']=='Hospitalized'].shape[0]
recovered = patients[patients['current_status']=='Recovered'].shape[0]
deaths = patients[patients['current_status']=='Deceased'].shape[0]

In [17]:
npat = patients[patients['current_status']=='Recovered']
pbar = npat['detected_state'].value_counts().reset_index()

In [15]:
pbar

Empty DataFrame
Columns: [detected_state, count]
Index: []